export default [
  { "name": "中国", "en": "China", "code": "CN", "dial_code": "+86" },
  { "name": "香港", "en": "Hong Kong", "code": "HK", "dial_code": "+852" },
  { "name": "澳门", "en": "Macau", "code": "MO", "dial_code": "+853" },
  { "name": "台湾", "en": "Taiwan", "code": "TW", "dial_code": "+886" },
  { "name": "日本", "en": "Japan", "code": "JP", "dial_code": "+81" },
  { "name": "韩国", "en": "South Korea", "code": "KR", "dial_code": "+82" },
  { "name": "朝鲜", "en": "North Korea", "code": "KP", "dial_code": "+850" },
  { "name": "美国", "en": "United States", "code": "US", "dial_code": "+1" },
  { "name": "加拿大", "en": "Canada", "code": "CA", "dial_code": "+1" },
  { "name": "英国", "en": "United Kingdom", "code": "GB", "dial_code": "+44" },
  { "name": "澳大利亚", "en": "Australia", "code": "AU", "dial_code": "+61" },
  { "name": "新西兰", "en": "New Zealand", "code": "NZ", "dial_code": "+64" },
  { "name": "法国", "en": "France", "code": "FR", "dial_code": "+33" },
  { "name": "德国", "en": "Germany", "code": "DE", "dial_code": "+49" },
  { "name": "意大利", "en": "Italy", "code": "IT", "dial_code": "+39" },
  { "name": "西班牙", "en": "Spain", "code": "ES", "dial_code": "+34" },
  { "name": "葡萄牙", "en": "Portugal", "code": "PT", "dial_code": "+351" },
  { "name": "瑞士", "en": "Switzerland", "code": "CH", "dial_code": "+41" },
  { "name": "奥地利", "en": "Austria", "code": "AT", "dial_code": "+43" },
  { "name": "荷兰", "en": "Netherlands", "code": "NL", "dial_code": "+31" },
  { "name": "比利时", "en": "Belgium", "code": "BE", "dial_code": "+32" },
  { "name": "卢森堡", "en": "Luxembourg", "code": "LU", "dial_code": "+352" },
  { "name": "爱尔兰", "en": "Ireland", "code": "IE", "dial_code": "+353" },
  { "name": "丹麦", "en": "Denmark", "code": "DK", "dial_code": "+45" },
  { "name": "挪威", "en": "Norway", "code": "NO", "dial_code": "+47" },
  { "name": "瑞典", "en": "Sweden", "code": "SE", "dial_code": "+46" },
  { "name": "芬兰", "en": "Finland", "code": "FI", "dial_code": "+358" },
  { "name": "冰岛", "en": "Iceland", "code": "IS", "dial_code": "+354" },
  { "name": "希腊", "en": "Greece", "code": "GR", "dial_code": "+30" },
  { "name": "塞浦路斯", "en": "Cyprus", "code": "CY", "dial_code": "+357" },
  { "name": "马耳他", "en": "Malta", "code": "MT", "dial_code": "+356" },
  { "name": "波兰", "en": "Poland", "code": "PL", "dial_code": "+48" },
  { "name": "捷克", "en": "Czech Republic", "code": "CZ", "dial_code": "+420" },
  { "name": "斯洛伐克", "en": "Slovakia", "code": "SK", "dial_code": "+421" },
  { "name": "匈牙利", "en": "Hungary", "code": "HU", "dial_code": "+36" },
  { "name": "罗马尼亚", "en": "Romania", "code": "RO", "dial_code": "+40" },
  { "name": "保加利亚", "en": "Bulgaria", "code": "BG", "dial_code": "+359" },
  { "name": "塞尔维亚", "en": "Serbia", "code": "RS", "dial_code": "+381" },
  { "name": "克罗地亚", "en": "Croatia", "code": "HR", "dial_code": "+385" },
  { "name": "斯洛文尼亚", "en": "Slovenia", "code": "SI", "dial_code": "+386" },
  { "name": "波黑", "en": "Bosnia and Herzegovina", "code": "BA", "dial_code": "+387" },
  { "name": "北马其顿", "en": "North Macedonia", "code": "MK", "dial_code": "+389" },
  { "name": "阿尔巴尼亚", "en": "Albania", "code": "AL", "dial_code": "+355" },
  { "name": "俄罗斯", "en": "Russia", "code": "RU", "dial_code": "+7" },
  { "name": "乌克兰", "en": "Ukraine", "code": "UA", "dial_code": "+380" },
  { "name": "白俄罗斯", "en": "Belarus", "code": "BY", "dial_code": "+375" },
  { "name": "土耳其", "en": "Turkey", "code": "TR", "dial_code": "+90" },
  { "name": "以色列", "en": "Israel", "code": "IL", "dial_code": "+972" },
  { "name": "巴勒斯坦", "en": "Palestine", "code": "PS", "dial_code": "+970" },
  { "name": "伊拉克", "en": "Iraq", "code": "IQ", "dial_code": "+964" },
  { "name": "伊朗", "en": "Iran", "code": "IR", "dial_code": "+98" },
  { "name": "叙利亚", "en": "Syria", "code": "SY", "dial_code": "+963" },
  { "name": "约旦", "en": "Jordan", "code": "JO", "dial_code": "+962" },
  { "name": "黎巴嫩", "en": "Lebanon", "code": "LB", "dial_code": "+961" },
  { "name": "沙特阿拉伯", "en": "Saudi Arabia", "code": "SA", "dial_code": "+966" },
  { "name": "科威特", "en": "Kuwait", "code": "KW", "dial_code": "+965" },
  { "name": "卡塔尔", "en": "Qatar", "code": "QA", "dial_code": "+974" },
  { "name": "阿联酋", "en": "United Arab Emirates", "code": "AE", "dial_code": "+971" },
  { "name": "阿曼", "en": "Oman", "code": "OM", "dial_code": "+968" },
  { "name": "也门", "en": "Yemen", "code": "YE", "dial_code": "+967" },
  { "name": "印度", "en": "India", "code": "IN", "dial_code": "+91" },
  { "name": "巴基斯坦", "en": "Pakistan", "code": "PK", "dial_code": "+92" },
  { "name": "孟加拉国", "en": "Bangladesh", "code": "BD", "dial_code": "+880" },
  { "name": "阿富汗", "en": "Afghanistan", "code": "AF", "dial_code": "+93" },
  { "name": "斯里兰卡", "en": "Sri Lanka", "code": "LK", "dial_code": "+94" },
  { "name": "尼泊尔", "en": "Nepal", "code": "NP", "dial_code": "+977" },
  { "name": "不丹", "en": "Bhutan", "code": "BT", "dial_code": "+975" },
  { "name": "马尔代夫", "en": "Maldives", "code": "MV", "dial_code": "+960" },
  { "name": "缅甸", "en": "Myanmar", "code": "MM", "dial_code": "+95" },
  { "name": "泰国", "en": "Thailand", "code": "TH", "dial_code": "+66" },
  { "name": "老挝", "en": "Laos", "code": "LA", "dial_code": "+856" },
  { "name": "柬埔寨", "en": "Cambodia", "code": "KH", "dial_code": "+855" },
  { "name": "越南", "en": "Vietnam", "code": "VN", "dial_code": "+84" },
  { "name": "马来西亚", "en": "Malaysia", "code": "MY", "dial_code": "+60" },
  { "name": "新加坡", "en": "Singapore", "code": "SG", "dial_code": "+65" },
  { "name": "印度尼西亚", "en": "Indonesia", "code": "ID", "dial_code": "+62" },
  { "name": "菲律宾", "en": "Philippines", "code": "PH", "dial_code": "+63" },
  { "name": "文莱", "en": "Brunei", "code": "BN", "dial_code": "+673" },
  { "name": "东帝汶", "en": "Timor-Leste", "code": "TL", "dial_code": "+670" },
  { "name": "蒙古", "en": "Mongolia", "code": "MN", "dial_code": "+976" },
  { "name": "哈萨克斯坦", "en": "Kazakhstan", "code": "KZ", "dial_code": "+7" },
  { "name": "乌兹别克斯坦", "en": "Uzbekistan", "code": "UZ", "dial_code": "+998" },
  { "name": "塔吉克斯坦", "en": "Tajikistan", "code": "TJ", "dial_code": "+992" },
  { "name": "吉尔吉斯斯坦", "en": "Kyrgyzstan", "code": "KG", "dial_code": "+996" },
  { "name": "土库曼斯坦", "en": "Turkmenistan", "code": "TM", "dial_code": "+993" },
  { "name": "埃及", "en": "Egypt", "code": "EG", "dial_code": "+20" },
  { "name": "苏丹", "en": "Sudan", "code": "SD", "dial_code": "+249" },
  { "name": "南苏丹", "en": "South Sudan", "code": "SS", "dial_code": "+211" },
  { "name": "利比亚", "en": "Libya", "code": "LY", "dial_code": "+218" },
  { "name": "突尼斯", "en": "Tunisia", "code": "TN", "dial_code": "+216" },
  { "name": "阿尔及利亚", "en": "Algeria", "code": "DZ", "dial_code": "+213" },
  { "name": "摩洛哥", "en": "Morocco", "code": "MA", "dial_code": "+212" },
  { "name": "毛里塔尼亚", "en": "Mauritania", "code": "MR", "dial_code": "+222" },
  { "name": "塞内加尔", "en": "Senegal", "code": "SN", "dial_code": "+221" },
  { "name": "冈比亚", "en": "Gambia", "code": "GM", "dial_code": "+220" },
  { "name": "几内亚", "en": "Guinea", "code": "GN", "dial_code": "+224" },
  { "name": "几内亚比绍", "en": "Guinea-Bissau", "code": "GW", "dial_code": "+245" },
  { "name": "塞拉利昂", "en": "Sierra Leone", "code": "SL", "dial_code": "+232" },
  { "name": "利比里亚", "en": "Liberia", "code": "LR", "dial_code": "+231" },
  { "name": "科特迪瓦", "en": "Ivory Coast", "code": "CI", "dial_code": "+225" },
  { "name": "加纳", "en": "Ghana", "code": "GH", "dial_code": "+233" },
  { "name": "多哥", "en": "Togo", "code": "TG", "dial_code": "+228" },
  { "name": "贝宁", "en": "Benin", "code": "BJ", "dial_code": "+229" },
  { "name": "布基纳法索", "en": "Burkina Faso", "code": "BF", "dial_code": "+226" },
  { "name": "尼日尔", "en": "Niger", "code": "NE", "dial_code": "+227" },
  { "name": "尼日利亚", "en": "Nigeria", "code": "NG", "dial_code": "+234" },
  { "name": "乍得", "en": "Chad", "code": "TD", "dial_code": "+235" },
  { "name": "中非共和国", "en": "Central African Republic", "code": "CF", "dial_code": "+236" },
  { "name": "喀麦隆", "en": "Cameroon", "code": "CM", "dial_code": "+237" },
  { "name": "赤道几内亚", "en": "Equatorial Guinea", "code": "GQ", "dial_code": "+240" },
  { "name": "加蓬", "en": "Gabon", "code": "GA", "dial_code": "+241" },
  { "name": "刚果（布）", "en": "Congo", "code": "CG", "dial_code": "+242" },
  { "name": "刚果（金）", "en": "DR Congo", "code": "CD", "dial_code": "+243" },
  { "name": "卢旺达", "en": "Rwanda", "code": "RW", "dial_code": "+250" },
  { "name": "布隆迪", "en": "Burundi", "code": "BI", "dial_code": "+257" },
  { "name": "坦桑尼亚", "en": "Tanzania", "code": "TZ", "dial_code": "+255" },
  { "name": "肯尼亚", "en": "Kenya", "code": "KE", "dial_code": "+254" },
  { "name": "乌干达", "en": "Uganda", "code": "UG", "dial_code": "+256" },
  { "name": "埃塞俄比亚", "en": "Ethiopia", "code": "ET", "dial_code": "+251" },
  { "name": "索马里", "en": "Somalia", "code": "SO", "dial_code": "+252" },
  { "name": "吉布提", "en": "Djibouti", "code": "DJ", "dial_code": "+253" },
  { "name": "厄立特里亚", "en": "Eritrea", "code": "ER", "dial_code": "+291" },
  { "name": "安哥拉", "en": "Angola", "code": "AO", "dial_code": "+244" },
  { "name": "纳米比亚", "en": "Namibia", "code": "NA", "dial_code": "+264" },
  { "name": "博茨瓦纳", "en": "Botswana", "code": "BW", "dial_code": "+267" },
  { "name": "津巴布韦", "en": "Zimbabwe", "code": "ZW", "dial_code": "+263" },
  { "name": "赞比亚", "en": "Zambia", "code": "ZM", "dial_code": "+260" },
  { "name": "莫桑比克", "en": "Mozambique", "code": "MZ", "dial_code": "+258" },
  { "name": "马拉维", "en": "Malawi", "code": "MW", "dial_code": "+265" },
  { "name": "马达加斯加", "en": "Madagascar", "code": "MG", "dial_code": "+261" },
  { "name": "毛里求斯", "en": "Mauritius", "code": "MU", "dial_code": "+230" },
  { "name": "塞舌尔", "en": "Seychelles", "code": "SC", "dial_code": "+248" },
  { "name": "科摩罗", "en": "Comoros", "code": "KM", "dial_code": "+269" },
  { "name": "南非", "en": "South Africa", "code": "ZA", "dial_code": "+27" },
  { "name": "莱索托", "en": "Lesotho", "code": "LS", "dial_code": "+266" },
  { "name": "斯威士兰", "en": "Eswatini", "code": "SZ", "dial_code": "+268" },
  { "name": "墨西哥", "en": "Mexico", "code": "MX", "dial_code": "+52" },
  { "name": "危地马拉", "en": "Guatemala", "code": "GT", "dial_code": "+502" },
  { "name": "洪都拉斯", "en": "Honduras", "code": "HN", "dial_code": "+504" },
  { "name": "萨尔瓦多", "en": "El Salvador", "code": "SV", "dial_code": "+503" },
  { "name": "尼加拉瓜", "en": "Nicaragua", "code": "NI", "dial_code": "+505" },
  { "name": "哥斯达黎加", "en": "Costa Rica", "code": "CR", "dial_code": "+506" },
  { "name": "巴拿马", "en": "Panama", "code": "PA", "dial_code": "+507" },
  { "name": "古巴", "en": "Cuba", "code": "CU", "dial_code": "+53" },
  { "name": "牙买加", "en": "Jamaica", "code": "JM", "dial_code": "+1" },
  { "name": "海地", "en": "Haiti", "code": "HT", "dial_code": "+509" },
  { "name": "多米尼加", "en": "Dominican Republic", "code": "DO", "dial_code": "+1" },
  { "name": "波多黎各", "en": "Puerto Rico", "code": "PR", "dial_code": "+1" },
  { "name": "特立尼达和多巴哥", "en": "Trinidad and Tobago", "code": "TT", "dial_code": "+1" },
  { "name": "巴哈马", "en": "Bahamas", "code": "BS", "dial_code": "+1" },
  { "name": "巴巴多斯", "en": "Barbados", "code": "BB", "dial_code": "+1" },
  { "name": "巴西", "en": "Brazil", "code": "BR", "dial_code": "+55" },
  { "name": "阿根廷", "en": "Argentina", "code": "AR", "dial_code": "+54" },
  { "name": "智利", "en": "Chile", "code": "CL", "dial_code": "+56" },
  { "name": "秘鲁", "en": "Peru", "code": "PE", "dial_code": "+51" },
  { "name": "哥伦比亚", "en": "Colombia", "code": "CO", "dial_code": "+57" },
  { "name": "委内瑞拉", "en": "Venezuela", "code": "VE", "dial_code": "+58" },
  { "name": "乌拉圭", "en": "Uruguay", "code": "UY", "dial_code": "+598" },
  { "name": "巴拉圭", "en": "Paraguay", "code": "PY", "dial_code": "+595" },
  { "name": "玻利维亚", "en": "Bolivia", "code": "BO", "dial_code": "+591" },
  { "name": "厄瓜多尔", "en": "Ecuador", "code": "EC", "dial_code": "+593" },
  { "name": "圭亚那", "en": "Guyana", "code": "GY", "dial_code": "+592" },
  { "name": "苏里南", "en": "Suriname", "code": "SR", "dial_code": "+597" },
  { "name": "澳大利亚", "en": "Australia", "code": "AU", "dial_code": "+61" },
  { "name": "斐济", "en": "Fiji", "code": "FJ", "dial_code": "+679" },
  { "name": "瓦努阿图", "en": "Vanuatu", "code": "VU", "dial_code": "+678" },
  { "name": "巴布亚新几内亚", "en": "Papua New Guinea", "code": "PG", "dial_code": "+675" },
  { "name": "所罗门群岛", "en": "Solomon Islands", "code": "SB", "dial_code": "+677" },
  { "name": "萨摩亚", "en": "Samoa", "code": "WS", "dial_code": "+685" },
  { "name": "汤加", "en": "Tonga", "code": "TO", "dial_code": "+676" },
  { "name": "基里巴斯", "en": "Kiribati", "code": "KI", "dial_code": "+686" },
  { "name": "密克罗尼西亚", "en": "Micronesia", "code": "FM", "dial_code": "+691" },
  { "name": "马绍尔群岛", "en": "Marshall Islands", "code": "MH", "dial_code": "+692" },
  { "name": "帕劳", "en": "Palau", "code": "PW", "dial_code": "+680" }
]